# Generated by Django 5.2.1 on 2025-05-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='nickname',
        ),
    ]
