# Generated by Django 5.2.1 on 2025-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_remove_profil_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='kategoriya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='qiyinlik',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=41),
        ),
    ]
