# Generated by Django 5.2.1 on 2025-05-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_challenge_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='davlat',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='rasm',
            new_name='img',
        ),
    ]
