# Generated by Django 5.2.1 on 2025-05-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_rename_davlat_profil_country_rename_rasm_profil_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='bloklangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='urinishlar_soni',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Urinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urinish_vaqti', models.DateTimeField(auto_now_add=True)),
                ('javob', models.CharField(max_length=255)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Urinishlar',
            },
        ),
    ]
