# Generated by Django 5.2.1 on 2025-05-10 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_challenge_bloklangan_challenge_urinishlar_soni_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='fayl',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
        migrations.AddField(
            model_name='challenge',
            name='bloklangan_vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='nomi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='ochko',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='qiyinlik',
            field=models.IntegerField(choices=[(1, 'Oson'), (2, 'Oʻrta'), (3, 'Qiyin')], default=1),
        ),
        migrations.AlterField(
            model_name='profil',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='img',
            field=models.ImageField(default='default_user.png', upload_to='profil_rasmlari'),
        ),
    ]
