# Generated by Django 5.2.1 on 2025-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0007_remove_challenge_fayl_remove_profil_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='qiyinlik',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
