# Generated by Django 5.2.1 on 2025-05-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0009_bloklanganchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='bloklangan',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='bloklangan_vaqt',
        ),
        migrations.AddField(
            model_name='challenge',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to='challenge_fayllari/'),
        ),
    ]
