# Generated by Django 5.2.1 on 2025-05-15 18:21

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0012_remove_profil_countryfailed_profil_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='country',
        ),
        migrations.AddField(
            model_name='profil',
            name='countryfailed',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Davlat'),
        ),
    ]
