# Generated by Django 5.2.1 on 2025-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0013_remove_profil_country_profil_countryfailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='countryfailed',
        ),
        migrations.AddField(
            model_name='profil',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
