# Generated by Django 5.2.1 on 2025-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0014_remove_profil_countryfailed_profil_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
