# Generated by Django 6.0.3 on 2026-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0015_kategoriya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategoriya',
        ),
        migrations.AlterField(
            model_name='profil',
            name='img',
            field=models.ImageField(default='arcana.jpg', upload_to='profil_rasmlari'),
        ),
    ]
