services:
  web:
    build: .
    container_name: django_web
    command: gunicorn imperium_ctf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    container_name: django_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
